### ISSUE TITLE
Failed to get power limits

### ISSUE THREAD

**Issue by kelthar** [nicehash/NiceHashQuickMiner#142]
When I QuickMiner on my Gigabyte 1660 Super I get this error message. Running it as admin, not using Afterburner.

Using: 461.40
OS: Windows 10 x64
Running it headless and remote in

[16:33:31][0x00002538][warning] device #0 | Failed to get power limits (issue with NVIDIA drivers!)
...
[16:37:31][0x00001f98][info] core | Device #0-0 speed: 31.25 MH/s   power: -3.00 W   efficiency: -10416947.200000 H/J

**Comment by nicehashdev** [comment]
Please, install latest 0.4.0.1 RC version and let me know if you still have this issue.

**Comment by nicehashdev** [comment]
Looks like your issue was solved with latest version. Closing.

**Comment by kelthar** [comment]
This problem is still present after installtin 0.4.0.3 RC. If I start afterburner, I can adjust power limit and change OC with that.

**Comment by kelthar** [comment]
[22:17:28][0x000016bc][warning] device #0 | Failed to get power limits (issue with NVIDIA drivers!)
[22:17:28][0x000016bc][info] core | Found (0) CUDA device: GeForce GTX 1660 SUPER

**Comment by nicehashdev** [comment]
I have made some improvements regarding that, please try following Excavator: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.1.2_RC/excavator_b723.zip
