### ISSUE TITLE
QuickMiner closes a few minutes after starting

### ISSUE THREAD

**Issue by bobjobob** [nicehash/NiceHashQuickMiner#22]
QuickMiner closes a few minutes after starting, causing the icon to disappear from the system tray and the NiceHash dashboard to show my rig as unavailable.  Excavator remains running and is still mining successfully, but I'm unable to control my rig remotely and locally cannot access the settings through the system tray.

Version:  0.3.0.6_RC
OS:  Windows 10 64bit
GPU:  GeForce RTX 3060 ti
Driver version:  461.40

[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/5977045/log.txt)

**Comment by nicehashdev** [comment]
Please, open your Windows Event Viewer and search for application errors - there will be one from NiceHashQuickMiner.exe; copy the content of the error here. Thank you!

**Comment by bobjobob** [comment]
I don't actually see any application errors from NiceHashQuickMiner.exe, or any events around the time the application started or stopped.  Maybe I'm looking in the wrong place?  I assumed it would be under [Event Viewer -> Windows Logs -> Application], but I can't find anything there or in any other location on Windows Event Viewer.

**Comment by nicehashdev** [comment]
Look for red error icons. You need to manually check each one because it does not say in the title that it is QuickMiner.

**Comment by bobjobob** [comment]
No red error icons, or events of any kind at the time.

I do have Webroot SecureAnywhere running, I'll investigate that next.  I have whitelisted QuickMiner and I don't see any logs indicating it would have stopped the application, but since disabling Webroot I've been running QuickMiner for over 15 minutes now without issues, which is longer than it typically lasts.  I'll let it run longer and keep troubleshooting later tonight to see if I can definitively tie the issue to Webroot.

**Comment by nicehashdev** [comment]
I assume this issue is fixed. Closing.

**Comment by bobjobob** [comment]
Apologies for the delay; I've spent the last couple days trading emails with Webroot customer support.

My issue is not resolved, though at this point it is clearly caused by the Webroot SecureAnywhere software.  Efforts by their customer support have so far been unsuccessful in resolving the issue, so I'll continue following up with them.  I'm comfortable calling this closed from the QuickMiner end, though.  Thanks for your help investigating.
