### ISSUE TITLE
[BUG] QM keeps searching for jobs with activated gamemode

### ISSUE THREAD

**Issue by UnPure** [nicehash/NiceHashQuickMiner#336]
I'm not sure if this might be intended but on the latest version it seems like QM keeps searching for jobs when the gamemode is activated. Before it was just showing disconnected, not it just keeps spamming the new job messages.

`net | daggerhashimoto | New job '00000000b3ab08c2', diff=0.197824 (clean)`

**To Reproduce**
Activate the miner, activate the gamemode, look at the console.

**Expected behavior**
Miner should stop everything if no other devices are mining while gamemode is activated.

**Version affected (please complete the following information):**
0.4.5.5RC

**Comment by nicehashdev** [comment]
How many GPUs do you have? Please provide log file. After activating logging, shut NHQM down, start it, then activate game mode, then deactivate so everything will be logged. Thanks!

**Comment by UnPure** [comment]
I enabled full logging and tried to disable game mode but I'm getting `Error: Not ready`
If I try to exit quickminer it tells me that game mode is still active and that I should disable game mode.
Now I'm stuck in between those.
I was able to start the miner and stop it again, now if I try to disable game mode it shows me `Error: No game mode detected`
I still cant exit quickminer though

**Comment by nicehashdev** [comment]
Try to reboot your PC. Probably your NVIDIA driver was updated and caused this mess. After reboot, things should be resolved.

**Comment by UnPure** [comment]
Rebooting my computer did not fix the problem. I'm using 2 GPUs for a while now in my system and always only used the main GPU with QM and game mode to enable/disable it but I never had any problems like this. Today is the first time that it keeps showing me new jobs while the game mode is enabled and nothing on my system changed like nvidia or other drivers. I always have excavator opened on my second monitor and would see if anything changes. It just showed that device #0 was disabled and then stopped doing anything until I deactivated game mode at a later time

**Comment by nicehashdev** [comment]
I would suggest you to do reinstall of NHQM, as it looks like you have lost default commands.json file.

**Comment by UnPure** [comment]
That is weird, I do have commands.json in `C:\Program Files\NiceHash\NiceHashQuickMiner` and I checked and made sure it is a valid .json. I reinstalled everything but the problems seem to still be there. New jobs and a small reported accepted speed (2-3MH/s) while game mode is active.

**Comment by nicehashdev** [comment]
Please, try latest 0.4.6.0 RC and report back your findings.

**Comment by UnPure** [comment]
Updated to 0.4.6.0 RC and it seems like the accepted speed is 0 now after enabling the game mode. New Jobs are still coming in though.

**Comment by nicehashdev** [comment]
Please, submit logs of the bug using latest version where it is clearly visible that the speed is 0. Thanks!
