### ISSUE TITLE
LHR unlock - working on evga FTW3 3080 lhr but not an Aurous rev 2.0

### ISSUE THREAD

**Issue by richardbaxterseo** [nicehash/NiceHashQuickMiner#808]
I've got an evga 3080 FTW3 lhr card running with the new update at 100mh/s. Incredible! Unfortunately a GIGABYTE AORUS rev 2 3080 on the same machine at 54. Does the LHR unlock not catch them all? FWIW I flashed the gigabyte with the evga bios and that made no difference. So, I returned it to the original bios. All ideas welcome!

**Comment by Bernkastel-0** [comment]
Gigabyte 3080 Gaming OC also does not unlock. Other cards work fine.

**Comment by leonw1090** [comment]
Same on my side 3060Ti  running perfect 100%LHR (60mh) using 100 gpu and 100 memory controler.

But the 3060 LHR only 27mh using 100% gpu and 33% memory controler.

**Comment by d-allin** [comment]
> Gigabyte 3080 Gaming OC also does not unlock. Other cards work fine (including Gigabyte 3060Ti).

Can confirm that my Gigabyte 3080 is likewise [not unlocking](https://i.imgur.com/T3QylY1.png).

**Comment by Destrifer** [comment]
Agree, Gigabyte 3080 Gaming OC 55mh only.

**Comment by ci9her** [comment]
My gigabtye 3080 10g turbo does not work too.

**Comment by barnowan** [comment]
Same with my Gigabyte 3080 10G.

**Comment by earner2021** [comment]
My Gigabyte 3080 10G TURBO, EAGLE, GAMING only 54 mh on any drivers

**Comment by Dohtar1337** [comment]
We already found the bug for this one. Will most likely be fixed in the next release

**Comment by Krishnan006** [comment]
Dohtar1337 still can't get full hashrate in gigabyte rtx 3080 oc 10gb card struck at 55mhs please kindly tell a solution if you know how to unlock to full hashrate, Thankyou
